# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: build a docker image
        run: docker build -t infra:v1 .

      - name: Push the docker image to the repository
        shell: bash
        env:
          user_name: ${{ secrets.DOCKER_USER_NAME }}
          user_password: ${{ secrets.DOCKER_USER_PASSWORD }}
        run: |
          docker login -u $user_name -p $user_password
          docker tag infra:v1 sainadh086/url-shortner:latest
          docker push sainadh086/url-shortner:latest
          echo "Success"
